name: 'health_pipeline'
version: '1.0.0'
config-version: 2

profile: 'health_pipeline'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

on-run-start:
  - "{{ create_schemas() }}"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  health_pipeline:
    uat:
      +materialized: view
      +schema: uat
    consumption:
      +materialized: table
      +schema: consumption