version: 2

sources:
  - name: raw
    database: health_db
    schema: raw
    tables:
      - name: raw_patient
        description: "Raw patient data loaded from CSV via Google Sheets"
        columns:
          - name: id
            tests:
              - unique
              - not_null

          - name: first_name
            tests:
              - not_null:
                  config:
                    severity: warn

          - name: last_name
            tests:
              - not_null:
                  config:
                    severity: warn

          - name: birth_date
            tests:
              - not_null:
                  config:
                    severity: warn

          - name: gender
            tests:
              - not_null:
                  config:
                    severity: warn
              - accepted_values:
                  config:
                    severity: warn
                  arguments:
                    values: ['male', 'female', 'other', 'unknown']

          - name: marital_status
            tests:
              - accepted_values:
                  config:
                    severity: warn
                  arguments:
                    values: ['married', 'single', 'divorced', 'widowed', 'unknown']

          - name: email
            tests:
              - not_null:
                  config:
                    severity: warn
              - unique:
                  config:
                    severity: warn

          - name: phone_number
            tests:
              - not_null:
                  config:
                    severity: warn

          - name: insurance_number
            tests:
              - not_null:
                  config:
                    severity: warn